#!/bin/bash

github_username="$1"
github_password="$2"
base_path="$3/"

echo "Please enter your github username"
read github_username
echo "Please enter your github password"
read github_password
echo "Please enter the path where Layla should be installed without /layla (example: /var/www/)"
read -e base_path

install_path="$base_path/layla/"

login=$(curl -u "$github_username:$github_password" "https://api.github.com/users/$github_username" | python -c 'import json,sys;obj=json.loads(sys.stdin.read());print obj["'"login"'"]')

echo "Forking layla/core"
curl -u "$login:$github_password" -X POST https://api.github.com/repos/layla/core/forks > /dev/null 2>&1
echo "Forking layla/admin"
curl -u "$login:$github_password" -X POST https://api.github.com/repos/layla/admin/forks > /dev/null 2>&1
echo "Forking layla/client"
curl -u "$login:$github_password" -X POST https://api.github.com/repos/layla/client/forks > /dev/null 2>&1
echo "Forking layla/components"
curl -u "$login:$github_password" -X POST https://api.github.com/repos/layla/components/forks > /dev/null 2>&1
echo "Forking layla/domain"
curl -u "$login:$github_password" -X POST https://api.github.com/repos/layla/domain/forks > /dev/null 2>&1

cd $base_path

echo "Cloning $(printf %q "$login")/core"
git clone "git@github.com:$(printf %q "$login")/core.git" layla  > /dev/null 2>&1

echo "Setting up .gitmodules"
cat > "$install_path.gitmodules" <<EOL
[submodule "bundles/client"]
	path = bundles/client
	url = git@github.com:${login}/client.git
[submodule "bundles/admin"]
	path = bundles/admin
	url = git@github.com:${login}/admin.git
[submodule "bundles/domain"]
	path = bundles/domain
	url = git@github.com:${login}/domain.git
[submodule "bundles/components"]
	path = bundles/components
	url = git@github.com:${login}/components.git 
EOL

cd $install_path

echo "Adding upsteam remote to the core repository"
git remote add upstream git@github.com:layla/core.git

echo "Initializing submodules..."
git submodule init > /dev/null 2>&1
echo "Updating submodules..."
git submodule update > /dev/null 2>&1

echo "Adding upsteam remote to the admin repository..."
cd "$install_path/bundles/admin" && git remote add upstream git@github.com:layla/admin.git
echo "Adding upsteam remote to the client repository..."
cd "$install_path/bundles/client" && git remote add upstream git@github.com:layla/client.git
echo "Adding upsteam remote to the components repository..."
cd "$install_path/bundles/components" && git remote add upstream git@github.com:layla/components.git
echo "Adding upsteam remote to the domain repository..."
cd "$install_path/bundles/domain" && git remote add upstream git@github.com:layla/domain.git

echo "Done!"